currency_regex: !ruby/regexp /\A[+-]?(\d+\.\d+)?\Z/
length:
  max_length_email: 150
  min_length_username: 6
  max_length_username: 50
  min_length_password: 6
size:
  page_record_medium: 6
admin:
  order_status:
    pending: 0
    accept: 1
    cancel: 2
    reject_: 3
  order_option:
    oldest: "0"
    newest: "1"
    status: "2"
  product_option:
    oldest: "1"
    newest: "2"
    price: "3"
    price_desc: "4"
    all: "5"
  product_sorts: [["Oldest", 1], ["Newest", 2], ["Price", 3], ["Desc Price", 4], ["All", 5]]
